################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: SoftPOS
  productionDescription: SoftPOS – Innovation at the Point of Sale
  whoIsItFor: For traditional small businesses and micro-merchants software point-of-sale (SoftPoS) technology removes the need for a standalone POS system and puts the power of payment acceptance into a device that is already in the business owner’s hand – their phone. 
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: SoftPOS
getStarted: /docs/getting-started.md
featuredFeatures:
  - title: Apple's Tap To Pay
    description: >
      Apple's tap to pay allows users to make contactless payments using their Apple devices, such as iPhone or Apple Watch, securely and conveniently.
#    tags: ["tag1", "tag2"]
#    bullets: ["Faster acceptance than credit or debit", "Biometric security", "Global offering and acceptance"]
#    links: ["docs/Getting-Started/Getting-Started-Wallets.md"]
    relatedDocs:
      - relatedDoc: 
        title: Apple Pay 
        description: Commerce Hub allows developers to quickly enable secure and convenient Apple Pay payments in their app or website.
        link: "docs/TTP/Apple-Pay/Apple-Pay-Getting-Started.md"
      # - relatedDoc: 
      #   title: Google Pay
      #   description: Commerce Hub allows developers to quickly enable secure and convenient Google Pay payments in their app or website. 
      #   link: "docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay.md"
      # - relatedDoc: 
      #   title: Samsung Pay
      #   description: Commerce Hub allows developers to quickly enable secure and convenient Samsung Pay payments in their app or website.
      #   link:
benefits:
  - title: Cost-Effective
    description: SoftPOS eliminates the need to invest in traditional POS hardware, significantly reducing upfront costs for businesses, especially small and medium-sized enterprises (SMEs).
  - title: Enhanced Mobility
    description: With SoftPOS, merchants can accept payments anywhere using their existing mobile devices, providing increased flexibility and mobility for on-the-go transactions.
  - title: Quick Deployment
    description: Implementing SoftPOS is quick and straightforward, with minimal setup requirements, enabling businesses to start accepting payments rapidly.   
  - title: Seamless Customer Experience
    description: SoftPOS ensures a seamless payment experience for customers, as they can conveniently use their contactless cards or devices for transactions.
  - Security and Compliance:
    decription: Fiserv's SoftPOS adheres to stringent security standards and EMV compliance, safeguarding sensitive customer data and protecting businesses from potential fraud.
